input:
  type: distributed
  path: DISTRIBUTED_WALLETS
  passphrases: ./passphrases.txt
  opts:
    threshold: 2
    peers:
      10: old1:9091
      20: old2:9091
      30: old3:9091
output:
  type: nd
  path: ND_WALLETS
  passphrases: ./passphrases.txt
log-level: debug

