distributed-wallets:
  path: ./walletsnew
  passphrases: ./passphrases.txt
  threshold: 2
  peers:
    10: old1:9091
    20: old2:9091
    30: old3:9091
nd-wallets:
  path: ./tests
  passphrases: ./passphrases.txt
log-level: debug
