input:
  store:
    path: ./distributed-to-keystore/distributed
  wallet:
    type: distributed
    threshold: 2
    peers:
      10:
        name: test1:9091
        passphrases:
          path: ./distributed-to-keystore/pass.txt
      20:
        name: test2:9091
        passphrases:
          path: ./distributed-to-keystore/pass.txt
      30:
        name: test3:9091
        passphrases:
          path: ./distributed-to-keystore/pass.txt
output:
  store:
    path: ./distributed-to-keystore/keystore
  wallet:
    type: keystore
    passphrases:
      path: ./distributed-to-keystore/pass.txt

log-level: debug
