name: Integration tests

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - 'master'

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          cache: true

      - name: Install dependencies
        run: go get .

      - name: Run build
        run: go build ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run golang lint
        uses: golangci/golangci-lint-action@v3
