name: Integration tests

on:
  pull_request:
    branches:
      - 'master'
  workflow_call:

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'

      - name: Install dependencies
        run: go get .

      - name: Run build
        run: go build ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run golang lint
        uses: golangci/golangci-lint-action@v3
