name: Key Verification Checker

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write # zizmor: ignore[excessive-permissions]
  issues: write # zizmor: ignore[excessive-permissions]

jobs:
  key-checker:
    uses: p2p-org/security-workflows/.github/workflows/key-checker.yaml@712d21de07f08789716c8fd6769e9ebcae9c1550 # main
    secrets: inherit # zizmor: ignore[secrets-inherit]
