name: Security Testing

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * SAT"

permissions:
  contents: read
  pull-requests: write # zizmor: ignore[excessive-permissions]
  issues: write # zizmor: ignore[excessive-permissions]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: p2p-org/security-workflows/.github/workflows/sast.yaml@712d21de07f08789716c8fd6769e9ebcae9c1550 # main
    secrets: inherit # zizmor: ignore[secrets-inherit]
  sca:
    uses: p2p-org/security-workflows/.github/workflows/sca.yaml@712d21de07f08789716c8fd6769e9ebcae9c1550 # main
    secrets: inherit # zizmor: ignore[secrets-inherit]
  security-quality-gate:
    uses: p2p-org/security-workflows/.github/workflows/security-quality-gate.yaml@712d21de07f08789716c8fd6769e9ebcae9c1550 # main
    secrets: inherit # zizmor: ignore[secrets-inherit]
    needs: [sast, sca]
    with:
      block: false
