name: Snyk Vulnerabilities Checker
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * 1'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#      - uses: actions/setup-go@v1
#        with:
#          go-version-file: './go.mod'
      - name: Init Snyk
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        run: |
#          snyk code test
#          snyk test --all-projects
#      - name: Run Snyk to check for vulnerabilities
#        run: |
#          snyk code test
#          snyk test --all-projects
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
