name: Snyk Vulnerabilities Checker
on:
  push:
    tags: ['v*']
  pull_request:
    branches: ['main']
#By default, a workflow only runs when a pull_request_target event's activity type is opened, synchronize, or reopened
  pull_request_target:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * 1'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: Run Snyk to check code for vulnerabilities
        run: |
          snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check dependencies for vulnerabilities
        run: |
          snyk test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
