name: Snyk Vulnerabilities Checker
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * 1'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version-file: './go.mod'
      - name: Run Snyk to check code for vulnerabilities
        run: |
          snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check dependencies for vulnerabilities
        continue-on-error: true
        run: |
          snyk test --severity-threshold=high --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
