name: Tests

# Runs via ci.yaml on pull requests and via release.yaml on tags
on:
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:
  go-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Repo Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: './go.mod'
          # This workflow also runs on release tags (cache poisoning)
          cache: false

      - name: Install dependencies
        run: go get .

      - name: Run build
        run: go build ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run golang lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

  nix-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7

      - name: Run nix flake check
        run: nix flake check
